name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        options:
            - dotnet-version: 3.1.x
              target-framework: netcoreapp3.1
            - dotnet-version: 6.0.x
              target-framework: net6.0

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.options.target-framework }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -f:RuntimeFrameworkVersion=${{ matrix.options.target-framework }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:RuntimeFrameworkVersion=${{ matrix.options.target-framework }}
