name: Publish

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        options:
            - dotnet-version: 3.1.x
              target-framework: netcoreapp3.1
            - dotnet-version: 6.0.x
              target-framework: net6.0
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.options.target-framework }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Pack
      run: dotnet pack -c Release --output .
    - name: Publish
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
